from enum import Enum


class DomainCode(str, Enum):
    VALIDATION_ERROR = "VALIDATION_ERROR"
    AUTH_REQUIRED = "AUTH_REQUIRED"
    AUTH_INVALID = "AUTH_INVALID"
    NOT_FOUND = "NOT_FOUND"
    NO_ACCESS = "NO_ACCESS"
    RATE_LIMITED = "RATE_LIMITED"
    UPSTREAM_UNAVAILABLE = "UPSTREAM_UNAVAILABLE"
    ARTIFACT_NOT_READY = "ARTIFACT_NOT_READY"
    OVERWRITE_CONFLICT = "OVERWRITE_CONFLICT"
    DOWNLOAD_FAILED = "DOWNLOAD_FAILED"
    AMBIGUOUS_RECORDING = "AMBIGUOUS_RECORDING"
    TRANSCRIPT_DISABLED = "TRANSCRIPT_DISABLED"
    RECORDING_DISABLED = "RECORDING_DISABLED"
    INTERNAL_ERROR = "INTERNAL_ERROR"

